# Generated by Django 5.0.10 on 2026-05-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_webuserpasswordstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgrouprole',
            name='allowed_branches',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
